@startuml Front Architecture

abstract class Article{}

class SimpleArticle{}
Article <|-- SimpleArticle

class ChildArticle{}
Article <|-- ChildArticle

class ArticleCollection{}
ArticleCollection "1" o-- "0..*" Article

class Page{}


abstract class Chunk{}
Chunk "1" o- "0..1" ArticleCollection

class SingleArticleChunk {}
Chunk <|-- SingleArticleChunk

class CategorizedArticlesChunk {}
Chunk <|-- CategorizedArticlesChunk

class HasChildArticlesChunk {}
Chunk <|-- HasChildArticlesChunk

class ChunkCollection{}
Page "1" o-- "0..1" ChunkCollection
ChunkCollection "1" o-- "0..*" Chunk

class ChunkFactory {}

@enduml
